// auto-generated by configen
// to add or remove properties, edit the mapping file'.
// README: https://github.com/theappbusiness/ConfigGenerator/blob/master/README.md
// timestamp: 2017-09-19 20:05:54 +0000

import Foundation
struct Dependency{

    let baseURL: URL? = URL(string: "http://dep.com/production")

    let key: String = "asdasdasdadssasdad"
}

struct EnvironmentConfig{

    let entryPointURL: URL? = URL(string: "http://example.com/production")

    let enableFileSharing: Bool = true

    let environment: Environment = .Production

    let dependency = Dependency()

    let analyticsKey: String = "haf6d9fha8v56abs"

    let adUnitPrefix: String = "production_ad_unit"

    let retryCount: Int = 4
}